version: '3'

services:
  vulnerable-web-app:
    build: .
    ports:
      - "6000:8080"

  secure_web_app:
    build: .
    ports: 
      - "7000:8080"

  waf:
    build: waf
    ports:
      - "8081:8080"
    depends_on:
      - secure_web_app
